<a href="https://colab.research.google.com/github/hemu2510/Python--udemy-course-/blob/main/Ndarrays_6th_feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array_a = np.array([4,8,12])
array_a

array([ 4,  8, 12])

In [ ]:
type(array_a)

numpy.ndarray

List vs Array

In [ ]:
list_a = [[2,4,8],[3,6,9]]
len(list_a)

2

In [ ]:
type(list_a)

list

In [ ]:
array_a = np.array(list_a)
type(array_a)

numpy.ndarray

Working with arrays

In [2]:
import numpy as np

In [4]:
matrix_A = np.array([[2,4,8],[3,6,9]])
matrix_A

array([[2, 4, 8],
       [3, 6, 9]])

slicing

In [8]:
matrix_A[0:2]

array([[2, 4, 8],
       [3, 6, 9]])

In [10]:
matrix_A[:,2:]

array([[8],
       [9]])

In [15]:
matrix_A[1:,1:]

array([[6, 9]])

Stepwise slicing

In [17]:
matrix_c = np.array([[1,1,1,1,1],[2,3,4,2,3],[4,6,5,4,2]])
matrix_c

array([[1, 1, 1, 1, 1],
       [2, 3, 4, 2, 3],
       [4, 6, 5, 4, 2]])

In [18]:
matrix_c[1:2]

array([[2, 3, 4, 2, 3]])

In [19]:
matrix_c[:,:]

array([[1, 1, 1, 1, 1],
       [2, 3, 4, 2, 3],
       [4, 6, 5, 4, 2]])

In [20]:
matrix_c[:,3]

array([1, 2, 4])

In [22]:
matrix_c[:,1]

array([1, 3, 6])

In [31]:
matrix_c[::-3,::2]

array([[4, 5, 2]])

Conditional slicing

In [32]:
matrix_c = np.array([[1,1,1,1,1],[2,3,4,2,3],[4,6,5,4,2]])
matrix_c

array([[1, 1, 1, 1, 1],
       [2, 3, 4, 2, 3],
       [4, 6, 5, 4, 2]])

In [33]:
matrix_c[:,1]

array([1, 3, 6])

In [35]:
matrix_c[:,0] > 1

array([False,  True,  True])

In [37]:
matrix_c[:,:]>1

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
matrix_c[matrix_c[:,:]>4]

array([6, 5])

In [43]:
matrix_c[matrix_c[:,:]==4]

array([4, 4, 4])

In [44]:
matrix_c[matrix_c[:,:]>=4]

array([4, 4, 6, 5, 4])

In [45]:
matrix_c[matrix_c[:,:]<=4]

array([1, 1, 1, 1, 1, 2, 3, 4, 2, 3, 4, 4, 2])

In [46]:
matrix_c[matrix_c[:,:]!=4]

array([1, 1, 1, 1, 1, 2, 3, 2, 3, 6, 5, 2])

In [49]:
matrix_c[matrix_c[:,:] % 4 == 2]

array([2, 2, 6, 2])

In [51]:
matrix_c[(matrix_c[:,:] % 4 == 2) | (matrix_c[:,:] <=2)]

array([1, 1, 1, 1, 1, 2, 2, 6, 2])

Dimensions and the Squeeze Function

In [52]:
matrix_D = np.array([[1,1,1,1,1],[2,3,4,2,3],[4,6,5,4,2]])
matrix_D

array([[1, 1, 1, 1, 1],
       [2, 3, 4, 2, 3],
       [4, 6, 5, 4, 2]])

In [54]:
type(matrix_D[1,2])

numpy.int64

In [55]:
print(matrix_D[1,2])

4


In [58]:
type(matrix_D[1,2:2])

numpy.ndarray

In [60]:
print(matrix_D[0,1:2])

[1]


In [61]:
print(matrix_D[0,0].shape)
print(matrix_D[0,1:2].shape)
print(matrix_D[0:1,1:2].shape)

()
(1,)
(1, 1)


In [66]:
print(matrix_D[0:1,0:1].squeeze())

1


In [70]:
 print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,1:2].squeeze().shape)
print(matrix_D[0:1,1:2].squeeze().shape)

()
()
()


Generating data with Numpy

np_empty()

In [76]:
import numpy as np
array_empty = np.empty(shape = (2,3))
array_empty

array([[3.06905150e-316, 0.00000000e+000, 1.50008929e+248],
       [1.50008929e+248, 5.95139232e+228, 3.12701935e-085]])

np_Zeros()

In [84]:
array_zeros = np.zeros(shape = (6,2))
array_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [85]:
array_zeros = np.zeros(shape = (6,2), dtype = np.int16)
array_zeros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

np_ones()

In [87]:
array_ones = np.ones(shape = (6,2), dtype = np.int16)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

np_full()

In [89]:
array_full = np.full(shape = (2,4), fill_value = 8)
array_full

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

like functions

In [91]:
array_h = np.array([[1,2,3,1,2],[3,4,3,2,1],[3,6,7,4,2]])
array_h

array([[1, 2, 3, 1, 2],
       [3, 4, 3, 2, 1],
       [3, 6, 7, 4, 2]])

In [92]:
array_empty_like = np.empty_like(array_h)
array_empty_like

array([[           88707337,                   0, 6998706448405521762,
                         97,     138258510208224],
       [    138258510208224, 2314885530818453536, 8316213867163312496,
        7019260658645360928, 7288829957272510579],
       [8318827349058480227, 7162257365610602612,  731680067765431919,
                         10,                 160]])

In [93]:
array_zeros_like = np.zeros_like(array_h)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [94]:
array_ones_like = np.ones_like(array_h)
array_ones_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [96]:
array_full_like = np.full_like(array_h, fill_value = 4)
array_full_like

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

np.arange()

In [100]:
array_rng = np.arange(21)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [105]:
array_rng = np.arange(start = 9 , stop = 10)
array_rng

array([9])

In [111]:
array_rng = np.arange(start = 2 , stop = 16 , step = 5)
array_rng

array([ 2,  7, 12])

In [116]:
array_rng = np.arange(start = 4 , stop = 15, step = 4.75 , dtype = np.float16)
array_rng

array([ 4.  ,  8.75, 13.5 ], dtype=float16)