<a href="https://colab.research.google.com/github/hemu2510/Python--udemy-course-/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
array_a = np.array([[1,4,5], [9,7,8]])
print(array_a)

[[1 4 5]
 [9 7 8]]


In [5]:
array_a[1]

array([9, 7, 8])

In [6]:
array_a[0][2]

5

In [7]:
array_a[:,1]

array([4, 7])

In [8]:
import numpy as np
array_b = np.array([2,4,5])
array_b[-2]

4

In [10]:
array_a

array([[1, 4, 5],
       [9, 7, 8]])

In [12]:
array_a[-2]

array([1, 4, 5])

In [13]:
array_a[0,1] = 10
array_a

array([[ 1, 10,  5],
       [ 9,  7,  8]])

In [15]:
array_a[:,2] = 12
array_a

array([[ 1, 12, 12],
       [ 9, 12, 12]])

In [16]:
list_a = [8,9,0]
array_a[1] = list_a
array_a

array([[ 1, 12, 12],
       [ 8,  9,  0]])

In [17]:
type(array_a[1])

numpy.ndarray

In [18]:
array_a[:] = 142
array_a

array([[142, 142, 142],
       [142, 142, 142]])

Elementwise properties of array

In [19]:
array_a = np.array([4,5,7])
array_a

array([4, 5, 7])

In [20]:
array_b = np.array([[1,4,2],[6,0,9]])
array_b

array([[1, 4, 2],
       [6, 0, 9]])

In [21]:
array_a * 3

array([12, 15, 21])

In [22]:
array_b +22

array([[23, 26, 24],
       [28, 22, 31]])

In [24]:
list_a = [1,4,2]
list_a + [7]


[1, 4, 2, 7]

In [25]:
array_a * array_b

array([[ 4, 20, 14],
       [24,  0, 63]])

In [26]:
array_a - array_b


array([[ 3,  1,  5],
       [-2,  5, -2]])

different datatypes Numpy can Support

In [30]:
array_a = np.array([[9,6,3],[8,4,2]])
array_a

array([[9, 6, 3],
       [8, 4, 2]])

In [37]:
array_a = np.array([[9,6,3],[8,4,2]], dtype = np.float64)
array_a

array([[9., 6., 3.],
       [8., 4., 2.]])

In [36]:
array_a = np.array([[9,6,3],[8,4,2]], dtype = np.complex64)
array_a

array([[9.+0.j, 6.+0.j, 3.+0.j],
       [8.+0.j, 4.+0.j, 2.+0.j]], dtype=complex64)

In [39]:
array_a = np.array([[9,6,3],[8,4,2]], dtype = np.bool_)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [41]:
array_a = np.array([[9,6,3],[8,4,2]], dtype = np.str_)
array_a

array([['9', '6', '3'],
       ['8', '4', '2']], dtype='<U1')

In [42]:
array_a = np.array([3,6,9])
array_a

array([3, 6, 9])

In [44]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [45]:
matrix_c = np.array([[2,4,8],[3,6,9]])
matrix_c

array([[2, 4, 8],
       [3, 6, 9]])

In [47]:
np.add(array_b,matrix_c)

array([[ 3,  5,  9],
       [ 5,  8, 11]])

In [53]:
np.median(matrix_c, axis = 1)

array([4., 6.])